version: '3.3'

services:
  site:
    image: raangularaspnetdb_site:latest
    depends_on:
      - api
    networks:  
      - app_net
    ports:
      - "4200:80"
    deploy:
      replicas: 1
    configs:
      - api_connect

  api:
    image: raangularaspnetdb_api:latest
    networks:  
      - app_net
    ports:
      - "5000:80"
    secrets:  
      - db_connect
    deploy:
      replicas: 1

networks:
  app_net:
    driver:   overlay

secrets:
  db_connect:
    file: ./ra-api/sql_connect.txt

configs:
  api_connect:
    file: ./ra-site/api_connect.txt